---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  # WARN: change also for cluster-autoscaler
  name: mbeham
  region: eu-west-1

cloudWatch:
  clusterLogging:
    enableTypes:
      - audit
      - authenticator
      - controllerManager

vpc:
  cidr: 10.10.0.0/16
  autoAllocateIPv6: false
  clusterEndpoints:
    publicAccess: true
    privateAccess: true
  nat:
    gateway: Single

iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: aws-load-balancer-controller
        namespace: kube-system
      wellKnownPolicies:
        awsLoadBalancerController: true
    - metadata:
        name: ebs-csi-controller-sa
        namespace: kube-system
      wellKnownPolicies:
        ebsCSIController: true
    - metadata:
        name: cert-manager
        namespace: cert-manager
      wellKnownPolicies:
        certManager: true
    - metadata:
        name: cluster-autoscaler
        namespace: kube-system
        labels:
          aws-usage: "cluster-ops"
      wellKnownPolicies:
        autoScaler: true
    - metadata:
        name: autoscaler-service
        namespace: kube-system
      attachPolicy: # inline policy can be defined along with `attachPolicyARNs`
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "autoscaling:DescribeAutoScalingGroups"
              - "autoscaling:DescribeAutoScalingInstances"
              - "autoscaling:DescribeLaunchConfigurations"
              - "autoscaling:DescribeTags"
              - "autoscaling:SetDesiredCapacity"
              - "autoscaling:TerminateInstanceInAutoScalingGroup"
              - "ec2:DescribeLaunchTemplateVersions"
            Resource: '*'

nodeGroups:
  - name: worker-ondemand
    instanceType: m5.large
    desiredCapacity: 3
    volumeSize: 100
    volumeType: gp3
    volumeEncrypted: true
    privateNetworking: true
    ssh:
      allow: true
      enableSsm: true
    iam:
      withAddonPolicies:
        cloudWatch: true
        ebs: true
        efs: true
        albIngress: true

  - name: ingress
    instanceType: m5.medium
    desiredCapacity: 2
    volumeSize: 20
    volumeType: gp3
    volumeEncrypted: true
    privateNetworking: true
    ssh:
      allow: true
      enableSsm: true
    iam:
      withAddonPolicies:
        cloudWatch: true
    taints:
      dedicated: "ingress:NoSchedule"
    labels:
      type: "ingress"

managedNodeGroups:
  - name: worker-spot
    minSize: 2
    maxSize: 10
    volumeEncrypted: true
    volumeSize: 100
    volumeType: gp3
    privateNetworking: true
    ssh:
      allow: true
      enableSsm: true
    tags:
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/cluster-mbeham: "owned"
    iam:
      withAddonPolicies:
        cloudWatch: true
        certManager: true
        ebs: true
        efs: true
        albIngress: true
    spot: true
    instanceTypes:
      - t3.small
      - t3.medium
      - t3.large

git:
  repo:
    url: "git@github.com:mbeham/mank8s_deployments.git"
    branch: main
    fluxPath: "cluster/mbeham/"
    user: "gitops"
    email: "gitops@jambit.space"
  operator:
    namespace: flux
    withHelm: true
